// Copyright 2021 Peter Williams <pwil3058@gmail.com> <pwil3058@bigpond.net.au>

pub static XPM: &[&str] = &[   "128 128 8 1",
    " 	c None",
    "A	c #FF0000",
    "H	c #DBDBDB",
    "I	c #DBDB00",
    "J	c #000024",
    "K	c #922424",
    "L	c #496D24",
    "M  c #00DB00",
    "                                                                                                                                ",
    "                                                                                                                                ",
    "                                                                                                                                ",
    "                                                                                                                                ",
    "                                                                                                                                ",
    "             JJJJJJJJJJJJJJJJJJJJ                        JJJJJJJJJJJJJJJJJJJJ                      JJJJJJJJJJJJJJJJJJJJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ                      JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ                      JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JHHHHHHHHHHHHHHHHHHJ                        JHHHHHHHHHHHHHHHHHHJ    MMMMMMMMMMMMMMM   JHHHHHHHHHHHHHHHHHHJ         ",
    "             JJJJJJJJJJJJJJJJJJJJ                        JJJJJJJJJJJJJJJJJJJJ    MMMMMMMMMMMMMMM   JJJJJJJJJJJJJJJJJJJJ         ",
    "            JJJJJJJJJJJJJJJJJJJJJJ                      JJJJJJJJJJJJJJJJJJJJJJ   MMMMMMMMMMMMMMM  JJJJJJJJJJJJJJJJJJJJJJ        ",
    "           JJJJJJJJJJJJJJJJJJJJJJJJ                    JJJJJJJJJJJJJJJJJJJJJJJJ  MMMMMMMMMMMMMMM JJJJJJJJJJJJJJJJJJJJJJJJ       ",
    "          JJJJJJJJJJJJJJJJJJJJJJJJJJ                  JJJJJJJJJJJJJJJJJJJJJJJJJJ MMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJ      ",
    "         JJJJJJJJJJJJJJJJJJJJJJJJJJJJ                JJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJ     ",
    "        JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ              JJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    ",
    "       JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ            JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ   ",
    "      JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ          JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ  ",
    "     JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ        JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ ",
    "    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ      JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJMMMMMMMMMMMMMMMJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJJJJJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIMMMMMMMMMMMMMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ    JIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  JLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJ",
    "   JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ  JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
    "                                                                                                                                ",
    "                                                                                                                                "
];

use pw_gix::{gdk_pixbuf, gtk};

#[allow(dead_code)]
pub fn pixbuf() -> gdk_pixbuf::Pixbuf {
    gdk_pixbuf::Pixbuf::from_xpm_data(XPM)
}

#[allow(dead_code)]
pub fn sized_pixbuf(size: i32) -> Option<gdk_pixbuf::Pixbuf> {
    pixbuf().scale_simple(size, size, gdk_pixbuf::InterpType::Bilinear)
}

#[allow(dead_code)]
pub fn sized_pixbuf_or(size: i32) -> gdk_pixbuf::Pixbuf {
    if let Some(pixbuf) = sized_pixbuf(size) {
        pixbuf
    } else {
        pixbuf()
    }
}

#[allow(dead_code)]
pub fn image() -> gtk::Image {
    gtk::Image::from_pixbuf(Some(&pixbuf()))
}

#[allow(dead_code)]
pub fn sized_image(size: i32) -> Option<gtk::Image> {
    pixbuf()
        .scale_simple(size, size, gdk_pixbuf::InterpType::Bilinear)
        .map(|pixbuf| gtk::Image::from_pixbuf(Some(&pixbuf)))
}

#[allow(dead_code)]
pub fn sized_image_or(size: i32) -> gtk::Image {
    if let Some(image) = sized_image(size) {
        image
    } else {
        image()
    }
}
