[package]
name = "apaint_gtk"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_derive = "1.0"

num = "0.2.0"

cairo-rs = "0.7.1"
gdk = "0.11.0"
gdk-pixbuf = "0.7.0"
gtk = "0.7.0"

apaint = { path = "../apaint" }
apaint_gtk_boilerplate = { path = "../apaint_gtk_boilerplate" }
apaint_cairo = { path = "../apaint_cairo" }

# TODO: change pw_gix dependency when it goes public
#pw_gix = { git = "https://github.com/pwil3058/rs_pw_gix.git" }
pw_gix = { path = "../../../CRATES/rs_pw_gix.git" }

# TODO: change normalised_angles dependency when it goes public
#normalised_angles = { git = "https://github.com/pwil3058/rs_normalised_angles.git" }
normalised_angles = { path = "../../../CRATES/rs_normalised_angles.git" }

# TODO: change colour_math dependency when it goes public
#colour_math = { git = "https://github.com/pwil3058/rs_colour_math.git" }
colour_math = { path = "../../../CRATES/rs_colour_math.git" }

# TODO: change colour_math dependency when it goes public
#float_plus = { git = "https://github.com/pwil3058/rs_float_plus.git" }
float_plus = { path = "../../../CRATES/rs_float_plus.git" }
