[package]
name = "apaint"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: change colour_math dependency when it goes public
#colour_math = { git = "https://github.com/pwil3058/rs_colour_math.git" }
colour_math = { path = "../../../CRATES/rs_colour_math.git" }
